name: Build and Deploy to Yandex Cloud

on:
  push:
    branches:
      - master # или main, в зависимости от вашей основной ветки

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Устанавливаем Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Укажите вашу версию Node.js

      # Шаг 3: Устанавливаем зависимости и собираем проект
      - name: Install dependencies and build
        run: npm ci && npm run build # Убедитесь, что у вас есть скрипт build в package.json

      # Шаг 4: Загружаем файлы в Yandex Cloud с явной настройкой
      - name: Deploy to Yandex Cloud
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ru-central1
        run: |
          aws s3 sync ./dist s3://my-bootstrap-starter --delete --endpoint-url https://storage.yandexcloud.net
